package view;

import Controller.CarrinhoController;
import entity.Carrinho;
import entity.ItemCarrinho;
import entity.Produto;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persist.ProdutoDAO;
import util.UnidadeFederacao;


/**
 *
 * @author andre
 */
public class TelaLoja extends javax.swing.JFrame {

    private String usuario_id;
    private DefaultTableModel tableModel;
    private ProdutoDAO prdao;
    private Carrinho carrinho;
    private CarrinhoController cntrl;

    /**
     * Creates new form TelaPrincipal
     */
    
    public TelaLoja() {
        initComponents();
    }
    public TelaLoja(String usuario_id, Carrinho carrinho) {

        this.usuario_id = usuario_id;
        this.carrinho = carrinho;
        cntrl = new CarrinhoController();
        initComponents();

        prdao = ProdutoDAO.getInstance();

        enderecoCheckBox();

        preencherComboBoxEstado();
        preencherComboBoxProdutos();

        configurarTabela();
        atualizarTabelaCarrinho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menusPainel = new javax.swing.JPanel();
        produtosPainel = new javax.swing.JPanel();
        produtosComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        adicionarBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();
        quantidadeLabel = new javax.swing.JLabel();
        quantidadeSpn = new javax.swing.JSpinner();
        limparBtn = new javax.swing.JButton();
        entregaPainel = new javax.swing.JPanel();
        entregaCheckBox = new javax.swing.JCheckBox();
        paisLabel = new javax.swing.JLabel();
        paisTextField = new javax.swing.JFormattedTextField();
        estadoComboBox = new javax.swing.JComboBox<>();
        estadoLabel = new javax.swing.JLabel();
        cidadeTextField = new javax.swing.JFormattedTextField();
        cidadeLabel = new javax.swing.JLabel();
        bairroTextField = new javax.swing.JFormattedTextField();
        bairroLabel = new javax.swing.JLabel();
        ruaTextField = new javax.swing.JFormattedTextField();
        ruaLabel = new javax.swing.JLabel();
        numeroTextField = new javax.swing.JFormattedTextField();
        numeroLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JFormattedTextField();
        dataEntregaTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        comprarBtn = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        produtosPainel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        produtosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Produtos");

        adicionarBtn.setText("Adicionar");
        adicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBtnActionPerformed(evt);
            }
        });

        removerBtn.setText("Remover do Carrinho");
        removerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtnActionPerformed(evt);
            }
        });

        quantidadeLabel.setText("Quantidade");

        quantidadeSpn.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                quantidadeSpnVetoableChange(evt);
            }
        });

        limparBtn.setText("Limpar Carrinho");

        javax.swing.GroupLayout produtosPainelLayout = new javax.swing.GroupLayout(produtosPainel);
        produtosPainel.setLayout(produtosPainelLayout);
        produtosPainelLayout.setHorizontalGroup(
            produtosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtosPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produtosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produtosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(produtosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantidadeSpn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeLabel))
                .addGap(18, 18, 18)
                .addComponent(adicionarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limparBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        produtosPainelLayout.setVerticalGroup(
            produtosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtosPainelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(produtosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(quantidadeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produtosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarBtn)
                    .addComponent(removerBtn)
                    .addComponent(quantidadeSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        entregaPainel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        entregaPainel.setPreferredSize(new java.awt.Dimension(1007, 86));

        entregaCheckBox.setText("Entrega");
        entregaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregaCheckBoxActionPerformed(evt);
            }
        });

        paisLabel.setText("País");

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        estadoLabel.setText("Estado");

        cidadeLabel.setText("Cidade");

        bairroLabel.setText("Bairro");

        ruaLabel.setText("Rua");

        numeroLabel.setText("Número");

        nomeLabel.setText("Nome do Endereço");

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        dataEntregaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataEntregaTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Dia de Entrega");

        javax.swing.GroupLayout entregaPainelLayout = new javax.swing.GroupLayout(entregaPainel);
        entregaPainel.setLayout(entregaPainelLayout);
        entregaPainelLayout.setHorizontalGroup(
            entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entregaPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entregaCheckBox)
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataEntregaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLabel)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisLabel))
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoLabel))
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeLabel))
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroLabel))
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruaLabel))
                .addGap(18, 18, 18)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroLabel)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        entregaPainelLayout.setVerticalGroup(
            entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entregaPainelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paisLabel)
                    .addComponent(estadoLabel)
                    .addComponent(cidadeLabel)
                    .addComponent(bairroLabel)
                    .addComponent(ruaLabel)
                    .addComponent(numeroLabel)
                    .addComponent(nomeLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(paisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entregaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(entregaCheckBox)
                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataEntregaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jRadioButton1.setText("Débito");

        jRadioButton3.setText("Pix");

        jRadioButton2.setText("Crédito");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Formas de Pagamento");

        comprarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comprarBtn.setText("Finalizar Compra");

        javax.swing.GroupLayout menusPainelLayout = new javax.swing.GroupLayout(menusPainel);
        menusPainel.setLayout(menusPainelLayout);
        menusPainelLayout.setHorizontalGroup(
            menusPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menusPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produtosPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entregaPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
                    .addGroup(menusPainelLayout.createSequentialGroup()
                        .addGroup(menusPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(menusPainelLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(comprarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menusPainelLayout.setVerticalGroup(
            menusPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produtosPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entregaPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menusPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(comprarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jMenu1.setText("Perfil");

        jMenuItem1.setText("Histórico de Compras");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menusPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menusPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void dataEntregaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataEntregaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataEntregaTextFieldActionPerformed

    private void entregaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregaCheckBoxActionPerformed
        enderecoCheckBox();
    }//GEN-LAST:event_entregaCheckBoxActionPerformed

    private void quantidadeSpnVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_quantidadeSpnVetoableChange
    }//GEN-LAST:event_quantidadeSpnVetoableChange

    private void adicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBtnActionPerformed
        adicionarProduto();
    }//GEN-LAST:event_adicionarBtnActionPerformed

    private void removerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtnActionPerformed
        deletarProduto();
    }//GEN-LAST:event_removerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JFormattedTextField bairroTextField;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JFormattedTextField cidadeTextField;
    private javax.swing.JToggleButton comprarBtn;
    private javax.swing.JFormattedTextField dataEntregaTextField;
    private javax.swing.JCheckBox entregaCheckBox;
    private javax.swing.JPanel entregaPainel;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limparBtn;
    private javax.swing.JPanel menusPainel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JFormattedTextField nomeTextField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JFormattedTextField numeroTextField;
    private javax.swing.JLabel paisLabel;
    private javax.swing.JFormattedTextField paisTextField;
    private javax.swing.JComboBox<String> produtosComboBox;
    private javax.swing.JPanel produtosPainel;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JSpinner quantidadeSpn;
    private javax.swing.JButton removerBtn;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JFormattedTextField ruaTextField;
    // End of variables declaration//GEN-END:variables

    private void deletarProduto() {
    }

    private void adicionarProduto() {
    }

    private void enderecoCheckBox() {
        boolean selecionado = entregaCheckBox.isSelected();
        dataEntregaTextField.setEnabled(false);
        nomeTextField.setEnabled(false);
        paisTextField.setEnabled(false);
        estadoComboBox.setEnabled(false);
        cidadeTextField.setEnabled(false);
        bairroTextField.setEnabled(false);
        ruaTextField.setEnabled(false);
        numeroTextField.setEnabled(false);

        if (selecionado) {
            dataEntregaTextField.setEnabled(true);
            nomeTextField.setEnabled(true);
            paisTextField.setEnabled(true);
            estadoComboBox.setEnabled(true);
            cidadeTextField.setEnabled(true);
            bairroTextField.setEnabled(true);
            ruaTextField.setEnabled(true);
            numeroTextField.setEnabled(true);
        }
    }

    private void preencherComboBoxProdutos() {
        produtosComboBox.removeAllItems();
        List<Produto> produtos = prdao.listarTudo();
        for (Produto produto : produtos) {
            produtosComboBox.addItem(produto.getMarca() + " " + produto.getNome()
                    + " - R$" + produto.getPreco());
        }
    }

    private void preencherComboBoxEstado() {
        estadoComboBox.removeAllItems();
        for (UnidadeFederacao estado : UnidadeFederacao.values()) {
            estadoComboBox.addItem(estado.getSigla());
        }
    }

    private void configurarTabela() {
        // Configura o DefaultTableModel para a jTable1
        tableModel = new DefaultTableModel(
                new Object[][]{}, // Dados iniciais (vazio)
                new String[]{"Produto", "Quantidade", "Valor"} // Nomes das colunas
        );

        jTable1.setModel(tableModel);
    }

    private void atualizarTabelaCarrinho() {
        tableModel.setRowCount(0);

        for (ItemCarrinho item : cntrl.listarProdutosCarrinho(carrinho.getId())) {
            Produto p = (Produto) prdao.read(item.getProdutoID());
            Object[] rowData = {
                p.getMarca() + " " + p.getNome(),
                item.getQuantidade(),
                cntrl.produtoValor(carrinho.getId(), item.getProdutoID())
            };
            tableModel.addRow(rowData);
        }
    }
}
