/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.ValidaCPF;
import entity.Pessoa;
import java.awt.Color;
import java.awt.Label;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import persist.PessoaDAO;

/**
 *
 * @author andre
 */
public class TelaLogin extends javax.swing.JFrame {

    private MaskFormatter cpfMask = null;
    private PessoaDAO pdao;

    /**
     * Creates new form NewJFrame1
     */
    public TelaLogin() {
        pdao = PessoaDAO.getInstance();
        initComponents();
        try {
            cpfMask = new MaskFormatter("###.###.###-##");
        } catch (Exception e) {
            e.printStackTrace();
        }
        warningSenhaTF.setVisible(false);
        warningSenhaTF.setEditable(false);
        warningLoginTF.setVisible(false);
        warningLoginTF.setEditable(false);
        apoioLabel.setVisible(false);
        warningLoginTF.setFocusable(false);
        warningSenhaTF.setFocusable(false);
        cpfLabel.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginFTF = new javax.swing.JFormattedTextField();
        senhaPF = new javax.swing.JPasswordField();
        senhaLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        warningLoginTF = new javax.swing.JTextField();
        warningSenhaTF = new javax.swing.JTextField();
        botoesPanel = new javax.swing.JPanel();
        entrarBtn = new javax.swing.JButton();
        ouLabel = new javax.swing.JLabel();
        cadastrarBtn = new javax.swing.JButton();
        apoioLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IFRStore");
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginFTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        loginFTF.setForeground(new java.awt.Color(153, 153, 153));
        loginFTF.setText("Exemplo: 123.456.789-00");
        loginFTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginFTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFTFloginFTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFTFloginFTFFocusLost(evt);
            }
        });
        loginFTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFTFloginFTFActionPerformed(evt);
            }
        });
        loginFTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginFTFKeyPressed(evt);
            }
        });

        senhaPF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        senhaPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaPFKeyPressed(evt);
            }
        });

        senhaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(0, 0, 0));
        senhaLabel.setText("Senha(mínimo 8)");

        cpfLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(0, 0, 0));
        cpfLabel.setText("CPF");

        warningLoginTF.setBackground(new java.awt.Color(247, 161, 161));
        warningLoginTF.setForeground(new java.awt.Color(79, 0, 0));
        warningLoginTF.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(168, 49, 49)));

        warningSenhaTF.setBackground(new java.awt.Color(247, 161, 161));
        warningSenhaTF.setForeground(new java.awt.Color(79, 0, 0));
        warningSenhaTF.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(168, 49, 49)));
        warningSenhaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                warningSenhaTFwarningSenhaTFKeyPressed(evt);
            }
        });

        botoesPanel.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10);
        flowLayout1.setAlignOnBaseline(true);
        botoesPanel.setLayout(flowLayout1);

        entrarBtn.setBackground(new java.awt.Color(184, 200, 217));
        entrarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        entrarBtn.setForeground(new java.awt.Color(73, 78, 82));
        entrarBtn.setText("Entrar");
        entrarBtn.setPreferredSize(new java.awt.Dimension(87, 33));
        entrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBtnActionPerformed(evt);
            }
        });
        botoesPanel.add(entrarBtn);

        ouLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ouLabel.setForeground(new java.awt.Color(73, 78, 82));
        ouLabel.setText("ou");
        ouLabel.setName(""); // NOI18N
        botoesPanel.add(ouLabel);

        cadastrarBtn.setBackground(new java.awt.Color(184, 200, 217));
        cadastrarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cadastrarBtn.setForeground(new java.awt.Color(73, 78, 82));
        cadastrarBtn.setText("Registrar-se");
        cadastrarBtn.setPreferredSize(new java.awt.Dimension(141, 33));
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });
        botoesPanel.add(cadastrarBtn);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfLabel)
                            .addComponent(loginFTF)
                            .addComponent(senhaPF)
                            .addComponent(warningSenhaTF)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(botoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(warningLoginTF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(senhaLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apoioLabel)
                .addGap(143, 143, 143))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apoioLabel)
                .addGap(21, 21, 21)
                .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginFTF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLoginTF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningSenhaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        logoLabel.setIcon(new javax.swing.ImageIcon("D:\\andre\\Documents\\Escola\\2023\\Programação\\AppMercado_BD\\AppMercadoBD\\src\\images\\logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginFTFloginFTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFTFloginFTFFocusGained
        if (loginFTF.getText().equals("Exemplo: 123.456.789-00")) {
            loginFTF.setText("");
            loginFTF.setForeground(Color.BLACK);
            try {
                cpfMask.install(loginFTF);
            } catch (Exception ex) {
                System.out.println("Erro = " + ex);
            }
        }
    }//GEN-LAST:event_loginFTFloginFTFFocusGained

    private void loginFTFloginFTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFTFloginFTFFocusLost
        cpfMask.uninstall();
        if (loginFTF.getText().equals("   .   .   -  ")) {
            loginFTF.setEditable(true);  // Torna o campo editável para remover a máscara
            loginFTF.setValue(null);      // Remove a máscara
            loginFTF.setText("Exemplo: 123.456.789-00");
            loginFTF.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_loginFTFloginFTFFocusLost

    private void loginFTFloginFTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFTFloginFTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFTFloginFTFActionPerformed

    private void warningSenhaTFwarningSenhaTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_warningSenhaTFwarningSenhaTFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_warningSenhaTFwarningSenhaTFKeyPressed

    private void entrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBtnActionPerformed
        String login = loginFTF.getText();
        String senha = senhaPF.getText();

        if (senha.isEmpty()) {
            apoioLabel.setVisible(true);
            warningSenhaTF.setText("Senha não informada!");
            warningSenhaTF.setVisible(true);
            senhaPF.grabFocus();
        }
        if(login.equals("   .   .   -  ")) {
            System.out.println("ola");
            apoioLabel.setVisible(true);
            warningLoginTF.setText("CPF não informado!");
            warningLoginTF.setVisible(true);
            cpfMask.install(loginFTF);
            return;
        }

        if (pdao.read(login) != null) {
            Pessoa p = (Pessoa) pdao.read(login);
            if (senha.equals(p.getUser().getSenha())) {
                new TelaLoja(p.getCpf()).setVisible(true);
                this.setVisible(false);
            } else {
                apoioLabel.setVisible(true);
                warningSenhaTF.setText("Senha incorreta!");
                warningSenhaTF.setVisible(true);
            }
        } else {
            apoioLabel.setVisible(true);
            warningLoginTF.setText("CPF não encontrado!");
            warningLoginTF.setVisible(true);
            cpfMask.install(loginFTF);
        }
        
    }//GEN-LAST:event_entrarBtnActionPerformed

    private void senhaPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaPFKeyPressed
        warningSenhaTF.setVisible(false);
        warningLoginTF.setVisible(false);
    }//GEN-LAST:event_senhaPFKeyPressed

    private void loginFTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginFTFKeyPressed
        warningSenhaTF.setVisible(false);
        warningLoginTF.setVisible(false);
    }//GEN-LAST:event_loginFTFKeyPressed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        new TelaCadastro().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaLogin telaLogin = new TelaLogin();
                telaLogin.setVisible(true);
                telaLogin.logoLabel.requestFocus();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apoioLabel;
    private javax.swing.JPanel botoesPanel;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JButton entrarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField loginFTF;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel ouLabel;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaPF;
    private javax.swing.JTextField warningLoginTF;
    private javax.swing.JTextField warningSenhaTF;
    // End of variables declaration//GEN-END:variables
}
